name: CI

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test (Node 18)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        env:
          # Ensure non-interactive behavior for Ink during CI
          IGLOO_DISABLE_RAW_MODE: '1'
        run: npm test

      - name: Build
        run: npm run build

