name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write        # create release, upload assets

jobs:
  release:
    name: Build, Test, Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Verify tag matches package.json version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PKG=$(node -e "console.log(JSON.parse(require('fs').readFileSync('package.json','utf8')).version)")
          echo "Tag: $TAG  package.json: v$PKG"
          if [ "$TAG" != "v$PKG" ]; then
            echo "Error: tag $TAG does not match package.json version v$PKG" >&2
            exit 1
          fi

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
